"""new upvote column added

Revision ID: a1a02b9c8de2
Revises: 148cf9c7e317
Create Date: 2022-05-13 00:03:05.284050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a02b9c8de2'
down_revision = '148cf9c7e317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upvotes', 'upvote')
    # ### end Alembic commands ###
