"""new columns added

Revision ID: a9ef3a378ea0
Revises: 8872236155f1
Create Date: 2022-05-11 12:32:06.368065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ef3a378ea0'
down_revision = '8872236155f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('post', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_pitch_post'), 'pitch', ['post'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitch_post'), table_name='pitch')
    op.drop_column('pitch', 'post')
    # ### end Alembic commands ###
